name: Upload Sample File

on:
  push:
    branches:
      - main

jobs:
  upload-sample:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload Sample File
        run: |
          $fileContent = "This is the content of the sample file."
          $fileContent | Out-File -FilePath sample.txt -Encoding UTF8

          # Add and commit the sample file
          git add sample.txt
          git commit -m "Add sample file"

          # Configure Git user information (replace with your info)
          git config user.email "rajeshjanapati@gmail.com"
          git config user.name "rajeshjanapati"

          # Push the changes to the repository
          git push -f origin main
